sima_online_store_picture:
    resource: "@SIMAOnlineStoreBundle/Controller/PictureController.php"
    type:     annotation

sima_online_store_article:
    resource: "@SIMAOnlineStoreBundle/Controller/ArticleController.php"
    type:     annotation

sima_online_store_employee:
    resource: "@SIMAOnlineStoreBundle/Controller/EmployeeController.php"
    type:     annotation

sima_online_store_enterprise:
    resource: "@SIMAOnlineStoreBundle/Controller/EnterpriseController.php"
    type:     annotation

sima_online_store_employee:
    resource: "@SIMAOnlineStoreBundle/Controller/EmployeeController.php"
    type:     annotation

sima_online_store_enterprise:
    resource: "@SIMAOnlineStoreBundle/Controller/EnterpriseController.php"
    type:     annotation

sima_online_store_article_model:
    resource: "@SIMAOnlineStoreBundle/Controller/ArticleModelController.php"
    type:     annotation

sima_online_store_technical_detail_item:
    resource: "@SIMAOnlineStoreBundle/Controller/TechnicalDetailItemController.php"
    type:     annotation

sima_online_store_characteristic_type:
    resource: "@SIMAOnlineStoreBundle/Controller/CharacteristicTypeController.php"
    type:     annotation

sima_online_store_category:
    resource: "@SIMAOnlineStoreBundle/Controller/CategoryController.php"
    type:     annotation

sima_online_store_article_price:
    resource: "@SIMAOnlineStoreBundle/Controller/ArticlePriceController.php"
    type:     annotation

sima_online_store_article:
    resource: "@SIMAOnlineStoreBundle/Controller/ArticleController.php"
    type:     annotation

sima_online_store:
    resource: "@SIMAOnlineStoreBundle/Resources/config/routing.yml"
    prefix: /

# admin_area:
#     resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
#     prefix: /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# IMPORTANT
# Import the following routes only if when you start the project
# those routes are not available :

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# _sonata_admin:
#     resource: .
#     type: sonata_admin
#     prefix: /admin
