<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * ArticleModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleModelRepository extends \Doctrine\ORM\EntityRepository
{
}
