<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{


	public function myFindAllDQL()
	{
		$query = $this->_em->createQuery('SELECT a , s.availableQuantity FROM SIMAOnlineStoreBundle:Article  a JOIN a.stocks s where a.id = s.article');
		$results = $query->getResult();

		return $results;
	}

}
