<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * ArticlePriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlePriceRepository extends \Doctrine\ORM\EntityRepository
{
}
