<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * CharacteristicTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
