<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * CheckoutEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckoutEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
