<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * EnterpriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnterpriseRepository extends \Doctrine\ORM\EntityRepository
{
}
