<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * InvoiceSupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceSupplierRepository extends \Doctrine\ORM\EntityRepository
{
}
