<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * InvoiceCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
