<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * QuotationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
