<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * QuotationItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationItemRepository extends \Doctrine\ORM\EntityRepository
{
}
