<?php

namespace SIMA\OnlineStoreBundle\Repository;

/**
 * TechnicalDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicalDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
